/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSchoolsRouteImport } from './routes/_authenticated/schools'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedLessonsRouteImport } from './routes/_authenticated/lessons'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCurriculumRouteImport } from './routes/_authenticated/curriculum'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedBadgesRouteImport } from './routes/_authenticated/badges'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students.$id'
import { Route as AuthenticatedSchoolsIdRouteImport } from './routes/_authenticated/schools.$id'
import { Route as AuthenticatedLessonsIdRouteImport } from './routes/_authenticated/lessons.$id'
import { Route as AuthenticatedClassesIdRouteImport } from './routes/_authenticated/classes.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolsRoute = AuthenticatedSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLessonsRoute = AuthenticatedLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCurriculumRoute = AuthenticatedCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBadgesRoute = AuthenticatedBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStudentsRoute,
} as any)
const AuthenticatedSchoolsIdRoute = AuthenticatedSchoolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSchoolsRoute,
} as any)
const AuthenticatedLessonsIdRoute = AuthenticatedLessonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLessonsRoute,
} as any)
const AuthenticatedClassesIdRoute = AuthenticatedClassesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClassesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/classes': typeof AuthenticatedClassesRouteWithChildren
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lessons': typeof AuthenticatedLessonsRouteWithChildren
  '/progress': typeof AuthenticatedProgressRoute
  '/schools': typeof AuthenticatedSchoolsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/classes/$id': typeof AuthenticatedClassesIdRoute
  '/lessons/$id': typeof AuthenticatedLessonsIdRoute
  '/schools/$id': typeof AuthenticatedSchoolsIdRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/classes': typeof AuthenticatedClassesRouteWithChildren
  '/curriculum': typeof AuthenticatedCurriculumRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lessons': typeof AuthenticatedLessonsRouteWithChildren
  '/progress': typeof AuthenticatedProgressRoute
  '/schools': typeof AuthenticatedSchoolsRouteWithChildren
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/classes/$id': typeof AuthenticatedClassesIdRoute
  '/lessons/$id': typeof AuthenticatedLessonsIdRoute
  '/schools/$id': typeof AuthenticatedSchoolsIdRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/badges': typeof AuthenticatedBadgesRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRouteWithChildren
  '/_authenticated/curriculum': typeof AuthenticatedCurriculumRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lessons': typeof AuthenticatedLessonsRouteWithChildren
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/schools': typeof AuthenticatedSchoolsRouteWithChildren
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/classes/$id': typeof AuthenticatedClassesIdRoute
  '/_authenticated/lessons/$id': typeof AuthenticatedLessonsIdRoute
  '/_authenticated/schools/$id': typeof AuthenticatedSchoolsIdRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/badges'
    | '/classes'
    | '/curriculum'
    | '/dashboard'
    | '/lessons'
    | '/progress'
    | '/schools'
    | '/students'
    | '/classes/$id'
    | '/lessons/$id'
    | '/schools/$id'
    | '/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/badges'
    | '/classes'
    | '/curriculum'
    | '/dashboard'
    | '/lessons'
    | '/progress'
    | '/schools'
    | '/students'
    | '/classes/$id'
    | '/lessons/$id'
    | '/schools/$id'
    | '/students/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/badges'
    | '/_authenticated/classes'
    | '/_authenticated/curriculum'
    | '/_authenticated/dashboard'
    | '/_authenticated/lessons'
    | '/_authenticated/progress'
    | '/_authenticated/schools'
    | '/_authenticated/students'
    | '/_authenticated/classes/$id'
    | '/_authenticated/lessons/$id'
    | '/_authenticated/schools/$id'
    | '/_authenticated/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools': {
      id: '/_authenticated/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof AuthenticatedSchoolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons': {
      id: '/_authenticated/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AuthenticatedLessonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum': {
      id: '/_authenticated/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AuthenticatedCurriculumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/badges': {
      id: '/_authenticated/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AuthenticatedBadgesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/schools/$id': {
      id: '/_authenticated/schools/$id'
      path: '/$id'
      fullPath: '/schools/$id'
      preLoaderRoute: typeof AuthenticatedSchoolsIdRouteImport
      parentRoute: typeof AuthenticatedSchoolsRoute
    }
    '/_authenticated/lessons/$id': {
      id: '/_authenticated/lessons/$id'
      path: '/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof AuthenticatedLessonsIdRouteImport
      parentRoute: typeof AuthenticatedLessonsRoute
    }
    '/_authenticated/classes/$id': {
      id: '/_authenticated/classes/$id'
      path: '/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof AuthenticatedClassesIdRouteImport
      parentRoute: typeof AuthenticatedClassesRoute
    }
  }
}

interface AuthenticatedClassesRouteChildren {
  AuthenticatedClassesIdRoute: typeof AuthenticatedClassesIdRoute
}

const AuthenticatedClassesRouteChildren: AuthenticatedClassesRouteChildren = {
  AuthenticatedClassesIdRoute: AuthenticatedClassesIdRoute,
}

const AuthenticatedClassesRouteWithChildren =
  AuthenticatedClassesRoute._addFileChildren(AuthenticatedClassesRouteChildren)

interface AuthenticatedLessonsRouteChildren {
  AuthenticatedLessonsIdRoute: typeof AuthenticatedLessonsIdRoute
}

const AuthenticatedLessonsRouteChildren: AuthenticatedLessonsRouteChildren = {
  AuthenticatedLessonsIdRoute: AuthenticatedLessonsIdRoute,
}

const AuthenticatedLessonsRouteWithChildren =
  AuthenticatedLessonsRoute._addFileChildren(AuthenticatedLessonsRouteChildren)

interface AuthenticatedSchoolsRouteChildren {
  AuthenticatedSchoolsIdRoute: typeof AuthenticatedSchoolsIdRoute
}

const AuthenticatedSchoolsRouteChildren: AuthenticatedSchoolsRouteChildren = {
  AuthenticatedSchoolsIdRoute: AuthenticatedSchoolsIdRoute,
}

const AuthenticatedSchoolsRouteWithChildren =
  AuthenticatedSchoolsRoute._addFileChildren(AuthenticatedSchoolsRouteChildren)

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBadgesRoute: typeof AuthenticatedBadgesRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRouteWithChildren
  AuthenticatedCurriculumRoute: typeof AuthenticatedCurriculumRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLessonsRoute: typeof AuthenticatedLessonsRouteWithChildren
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedSchoolsRoute: typeof AuthenticatedSchoolsRouteWithChildren
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBadgesRoute: AuthenticatedBadgesRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRouteWithChildren,
  AuthenticatedCurriculumRoute: AuthenticatedCurriculumRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLessonsRoute: AuthenticatedLessonsRouteWithChildren,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedSchoolsRoute: AuthenticatedSchoolsRouteWithChildren,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
